INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'electronic', '驚き', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=200');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'pop', '退屈', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=201');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'electronic', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=202');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'r&b', '驚き', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=203');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'pop', '楽しい', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=204');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'pop', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=205');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'electronic', '安心', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=206');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Someone Like You', 'Adele', 'r&b', '喜び', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=207');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'r&b', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=208');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'hip-hop', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=209');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'electronic', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=210');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'hip-hop', '悲しみ', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=211');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'r&b', '安心', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=212');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'hip-hop', '不安', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=213');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'hip-hop', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=214');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'electronic', '喜び', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=215');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'electronic', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=216');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'rock', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=217');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Someone Like You', 'Adele', 'rock', '悲しみ', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=218');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'hip-hop', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=219');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'r&b', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=220');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'hip-hop', '驚き', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=221');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'electronic', '楽しい', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=222');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Someone Like You', 'Adele', 'pop', '不安', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=223');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'pop', '怒り', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=224');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Someone Like You', 'Adele', 'hip-hop', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=225');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'hip-hop', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=226');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'rock', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=227');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'electronic', '退屈', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=228');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'electronic', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=229');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'pop', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=230');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'r&b', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=231');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'r&b', '不安', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=232');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'hip-hop', '平静', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=233');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'r&b', '退屈', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=234');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'r&b', '不安', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=235');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'pop', '退屈', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=236');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'hip-hop', '不安', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=237');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'hip-hop', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=238');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'pop', '悲しみ', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=239');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'pop', '退屈', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=240');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'hip-hop', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=241');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'hip-hop', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=242');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'electronic', '退屈', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=243');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'r&b', '退屈', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=244');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'pop', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=245');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'rock', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=246');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'electronic', '楽しい', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=247');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'pop', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=248');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'pop', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=249');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'hip-hop', '怒り', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=250');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'hip-hop', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=251');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'hip-hop', '安心', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=252');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'r&b', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=253');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'hip-hop', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=254');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'electronic', '不安', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=255');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'r&b', '安心', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=256');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'hip-hop', '安心', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=257');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'pop', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=258');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'hip-hop', '安心', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=259');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'hip-hop', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=260');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'pop', '驚き', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=261');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Someone Like You', 'Adele', 'rock', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=262');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'r&b', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=263');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'electronic', '安心', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=264');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'r&b', '驚き', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=265');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'hip-hop', '不安', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=266');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'hip-hop', '怒り', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=267');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'hip-hop', '楽しい', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=268');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'rock', '退屈', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=269');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'pop', '不安', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=270');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'pop', '平静', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=271');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'electronic', '驚き', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=272');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'pop', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=273');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'rock', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=274');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'hip-hop', '喜び', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=275');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'electronic', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=276');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'rock', '喜び', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=277');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'hip-hop', '喜び', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=278');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'hip-hop', '退屈', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=279');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'r&b', '退屈', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=280');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'electronic', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=281');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'r&b', '安心', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=282');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'pop', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=283');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'hip-hop', '不安', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=284');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'r&b', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=285');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'pop', '悲しみ', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=286');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'r&b', '悲しみ', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=287');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'hip-hop', '喜び', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=288');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'hip-hop', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=289');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'pop', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=290');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'r&b', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=291');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'electronic', '喜び', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=292');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Someone Like You', 'Adele', 'pop', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=293');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'electronic', '悲しみ', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=294');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'electronic', '喜び', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=295');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'rock', '退屈', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=296');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'electronic', '喜び', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=297');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'rock', '悲しみ', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=298');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'hip-hop', '安心', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=299');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'hip-hop', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=300');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'electronic', '退屈', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=301');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'pop', '喜び', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=302');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'hip-hop', '怒り', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=303');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'electronic', '楽しい', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=304');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'electronic', '平静', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=305');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'electronic', '不安', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=306');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'hip-hop', '喜び', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=307');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'rock', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=308');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'pop', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=309');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'electronic', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=310');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'pop', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=311');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'rock', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=312');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'pop', '喜び', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=313');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'hip-hop', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=314');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'r&b', '悲しみ', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=315');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'pop', '楽しい', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=316');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'pop', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=317');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'hip-hop', '驚き', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=318');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'r&b', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=319');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'pop', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=320');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'hip-hop', '悲しみ', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=321');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'rock', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=322');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'electronic', '不安', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=323');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'pop', '不安', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=324');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'hip-hop', '楽しい', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=325');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'r&b', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=326');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'electronic', '喜び', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=327');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'electronic', '平静', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=328');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'pop', '平静', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=329');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'pop', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=330');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'hip-hop', '平静', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=331');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'r&b', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=332');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'pop', '平静', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=333');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'pop', '不安', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=334');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'hip-hop', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=335');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'hip-hop', '怒り', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=336');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'pop', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=337');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'electronic', '平静', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=338');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'r&b', '退屈', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=339');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'pop', '喜び', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=340');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'r&b', '喜び', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=341');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'pop', '平静', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=342');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'hip-hop', '悲しみ', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=343');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'r&b', '怒り', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=344');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'rock', '楽しい', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=345');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'electronic', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=346');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'rock', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=347');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'hip-hop', '退屈', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=348');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Bad Guy', 'Billie Eilish', 'pop', '悲しみ', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=349');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'rock', '不安', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=350');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'rock', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=351');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'rock', '驚き', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=352');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'hip-hop', '悲しみ', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=353');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'hip-hop', '平静', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=354');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'pop', '喜び', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=355');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'rock', '安心', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=356');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'hip-hop', '不安', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=357');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'pop', '喜び', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=358');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'r&b', '怒り', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=359');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'pop', '安心', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=360');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'hip-hop', '驚き', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=361');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'rock', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=362');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'pop', '平静', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=363');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'rock', '退屈', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=364');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'pop', '驚き', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=365');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'pop', '喜び', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=366');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'r&b', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=367');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'hip-hop', '悲しみ', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=368');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'pop', '楽しい', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=369');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'hip-hop', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=370');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'electronic', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=371');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Lemon', '米津玄師', 'rock', '平静', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=372');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'rock', '不安', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=373');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'hip-hop', '悲しみ', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=374');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'electronic', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=375');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'electronic', '悲しみ', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=376');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'rock', '驚き', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=377');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('春を告げる', 'yama', 'hip-hop', '退屈', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=378');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'r&b', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=379');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Pretender', 'Official髭男dism', 'electronic', '退屈', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=380');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'hip-hop', '安心', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=381');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shape of You', 'Ed Sheeran', 'rock', '安心', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=382');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('紅蓮華', 'LiSA', 'rock', '不安', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=383');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'pop', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=384');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Stay', 'Justin Bieber', 'rock', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=385');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'rock', '喜び', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=386');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'r&b', '平静', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=387');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'rock', '喜び', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=388');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'r&b', '悲しみ', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=389');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('アイノカタチ', 'MISIA', 'pop', '喜び', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=390');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('ドライフラワー', '優里', 'pop', '怒り', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=391');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('夜に駆ける', 'YOASOBI', 'rock', '不安', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=392');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Levitating', 'Dua Lipa', 'electronic', '安心', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=393');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('猫', 'DISH//', 'hip-hop', '楽しい', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=394');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Uptown Funk', 'Bruno Mars', 'r&b', '悲しみ', '50~60代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=395');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Someone Like You', 'Adele', 'pop', '安心', '70代以上', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=396');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'rock', '怒り', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=397');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Blinding Lights', 'The Weeknd', 'rock', '楽しい', '30~40代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=398');
INSERT INTO songs (title, artist, genre, mood, age_group, file_path) VALUES ('Shallow', 'Lady Gaga', 'rock', '楽しい', '10~20代', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=399');